### ISSUE TITLE
Segmentation fault (core dumped) when running test.py

### ISSUE THREAD

**Issue by shenliyan** [SSGAalto/minionn#6]
Hi,
when i input "python3 test.py", I got an error. I have modified cfg['parallel'] = False. 

[root@localhost lib]# python3 test.py
........
g++ -pthread -shared -B /root/miniconda3/compiler_compat -L/root/miniconda3/lib -Wl,-rpath=/root/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/tmpn14w7ygm/home/sly/minionn/lib/minionnMath.o /tmp/tmpn14w7ygm/home/sly/minionn/lib/minionnCrypto.o /tmp/tmpn14w7ygm/home/sly/minionn/lib/minionnABY.o /tmp/tmpn14w7ygm/home/sly/minionn/lib/.rendered.minionn.o -lseal bin/libaby.a -lssl -lcrypto -lgmp -lgmpxx -lpthread -o /tmp/tmpn14w7ygm/minionn.cpython-37m-x86_64-linux-gnu.so
copying /tmp/tmpn14w7ygm/minionn.cpython-37m-x86_64-linux-gnu.so -> /home/sly/minionn/lib
Segmentation fault (core dumped)

What's going on? Thanks!

**Comment by fritzalder** [comment]
That is a little bit tricky, I don't know what is going on there. Maybe try to test SEAL and ABY independently. E.g. take some elements out of the minionn.cpp and only test minionnMath for example. If that works, add minionnCrypto etc.
That way you at least see if the error is with Python, C++, SEAL, or ABY (or anything else).

**Comment by shenliyan** [comment]
Hi,
when i input "python3 test.py", There is an error. 
[root@localhost lib]# python3 test.py

g++ -pthread -shared -B /root/miniconda3/compiler_compat -L/root/miniconda3/lib -Wl,-rpath=/root/miniconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/tmpyjs5w9nr/home/sly/lib/lib/minionnMath.o /tmp/tmpyjs5w9nr/home/sly/lib/lib/minionnCrypto.o /tmp/tmpyjs5w9nr/home/sly/lib/lib/minionnABY.o /tmp/tmpyjs5w9nr/home/sly/lib/lib/.rendered.minionn.o -lseal bin/libaby.a -lssl -lcrypto -lgmp -lgmpxx -lpthread -o /tmp/tmpyjs5w9nr/minionn.cpython-37m-x86_64-linux-gnu.so -shared
copying /tmp/tmpyjs5w9nr/minionn.cpython-37m-x86_64-linux-gnu.so -> /home/sly/lib/lib
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    m = cppimport.imp("minionn")
  File "/root/miniconda3/lib/python3.7/site-packages/cppimport/importer.py", line 84, in imp
    return imp_from_filepath(filepath, fullname)
  File "/root/miniconda3/lib/python3.7/site-packages/cppimport/importer.py", line 78, in imp_from_filepath
    load_module(module_data)
  File "/root/miniconda3/lib/python3.7/site-packages/cppimport/importer.py", line 41, in load_module
    _load_module(module_data)
  File "/root/miniconda3/lib/python3.7/site-packages/cppimport/importer.py", line 34, in _load_module
    module_data['module'] = importlib.import_module(module_data['fullname'])
  File "/root/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/sly/lib/lib/minionn.cpython-37m-x86_64-linux-gnu.so: undefined symbol: EVP_CIPHER_CTX_init

What's going on? I have installed libssl libcrypto, Thanks!

**Comment by Cestlaviez** [comment]
Hi @shenliyan 
I think you might need to update SEAL to the latest updated version.
Since when I ran this program, the problem is from the SEAL.

**Comment by LiuJingjinga** [comment]
@shenliyan Hello, I have the same problem.
How did you solve it?

**Comment by fritzalder** [comment]
If you solve this, I am happy to accept pull requests. I am not actively supporting this code anymore but I am willing to put in some effort to keep the code usable.
